# 此工作流程将安装 Python 依赖项、运行测试并使用各种 Python 版本进行 lint
# 有关更多信息，请参阅：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

名称： Python包

在：
  推：
    分支：[  “主要”  ]
  拉请求：
    分支：[  “主要”  ]

工作：
  建造：

    运行： ubuntu-latest
    战略：
      快速失败：false
      矩阵：
        python版本：[ “3.9” ， “3.10” ， “3.11” ]

    脚步：
    -使用： actions/checkout@v4
    -名称：设置 Python $ { { matrix.python-version } }
      使用： actions/setup-python@v3
      和：
        python-版本: $ { {矩阵.python-版本} }
    -名称：安装依赖项
      运行：|
        python -m pip install --升级 pip
        python -m pip 安装 flake8 pytest
        if [ -f 要求.txt ]; 然后 pip install -rrequirements.txt；菲
    -名称: Lint with flake8
      运行：|
        # 如果存在 Python 语法错误或未定义的名称，则停止构建
        片8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero 将所有错误视为警告。GitHub 编辑器的宽度为 127 个字符
        片8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    -名称：使用 pytest 进行测试
      运行：|
        py测试
